"""The harness-log parity pins: recorded scenarios, byte-for-byte.

``docs/design/ui-monitor.md`` §4.8 ("Harness log parity") names the
``harness_log`` narration as the diff-check for the VM/brain split: *the same
recorded scenario must produce the same log lines before and after, modulo
lines the phase explicitly renames*. §6.1's and §6.2's "done when" clauses both
cash that promise in, so the recording has to exist BEFORE the refactor does -
this file is that recording, taken against the pre-split controller.

Which makes it a different animal to ``test_finish_evaluation.py``. That suite
asserts the RULES (what arms, what fires, what the gate does) and phrases its
assertions as ``view.logged("...")`` substring probes precisely so a reworded
sentence does not fail it. This one asserts the NARRATION: every scenario walks
a whole path through the loop with pure-Python calls and pins the exact list of
lines it produced, in order, as literals. A refactor that changes the wording,
the order, the count, or which decision writes a line fails here - and that is
the intended failure, not a brittleness to route around.

The literals were generated by running each scenario once against the
controller as it stood at the head of the plan (commit ``c341a82``, phase 0
built, nothing of the split landed) and pasting the output in.

**Changing a line in this file is a decision, not a fix.** The only legitimate
reason is a phase that *explicitly* renames a harness line and says so in its
section of ``ui-monitor.md``; then the literal moves and the phase note records
it. Anything else - a line vanishing, a new line appearing between two others,
a state entry losing its reason - is the regression §4.8 exists to catch.

Every scenario also pins the ``LoopState`` sequence the view was painted with,
because the rail and the log are one act (``set_loop_state`` writes both under
the same lock) and a refactor that keeps one while dropping the other is
exactly the half-done inversion phase 2 risks. And ``on_fire`` is a recorder in
every scenario, so the one-shot fire of §4.1 is pinned alongside: exactly one
fire on every path that reaches the harvest, and none on the paths that do not.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from agentclip.driver.automation.controller import AutomationController
from agentclip.driver.automation.finish import (
    SEND_ARM_MIN_DIFF,
    SEND_ARM_TICKS,
    SEND_GATE_TIMEOUT_TICKS,
)
from agentclip.driver.automation.loop_state import LoopState
from agentclip.driver.screen.busy import BusyProbe, BusyState
from agentclip.driver.screen.profile import TemplateKind
from agentclip.driver.screen.stale import StaleProbe, StaleState

from .conftest import FakeAutomationView

# The two appearances any of this turns on: a copy button is what a finish has
# to click, a send button is what makes a gate exist at all.
COPY = TemplateKind.COPY
SEND_READY = TemplateKind.SEND_READY

# The two sentences the shell's delivery writes on its way out of IDLE
# (``copy_outbound`` and ``deliver``'s pasted branch). Quoted here rather than
# imported because there is nothing to import - they are literals at their call
# sites, and a scenario that made them up would pin fiction.
OUTBOUND_READY = "an outbound payload is ready to go into the chat box"
PASTE_LANDED = "the payload was pasted into the chat box"
PASTE_MISSED = "the chat box was focused but the synthetic Ctrl+V did not go through"


@dataclass
class Scenario:
    """One controller, its view, and everything it fired at.

    Only synchronous mutators are ever called on it: ``feed_probe`` (the poll
    loop's own seam) plus the handful of bookkeeping calls a shell makes from
    the UI thread. Nothing here touches the OS-acting coroutines, so a scenario
    is a few microseconds of pure state and reproduces exactly.
    """

    controller: AutomationController
    view: FakeAutomationView
    fires: list[None] = field(default_factory=list)

    # -- the probes, as the poller pushes them --------------------------------

    def busy(self, state: BusyState) -> None:
        """One busy-appearance probe, its per-frame evidence honest to the
        verdict (the disagreement is ``test_finish_evaluation``'s subject)."""
        self.controller.feed_probe("busy", BusyProbe(state, 0.2, state is BusyState.MATCH))

    def stale(self, state: StaleState, *, diff: float = 0.001) -> None:
        self.controller.feed_probe("stale", StaleProbe(state, diff, 0))

    def send_ready(self, found: bool | None) -> None:
        self.controller.feed_probe("send_ready", found)

    def big_delta(self) -> None:
        """One tick of the sustained large-delta run the stale detector arms on."""
        self.stale(StaleState.CHANGING, diff=SEND_ARM_MIN_DIFF)

    # -- the shell's own moves ------------------------------------------------

    def paste_landed(self) -> None:
        """The ordinary auto-insert, exactly as ``deliver`` narrates it: the
        loop leaves IDLE, the Ctrl+V lands, and the reply gate opens last."""
        self.controller.set_loop_state(LoopState.AUTO_INSERT, OUTBOUND_READY)
        self.controller.set_loop_state(LoopState.WAIT_SEND, PASTE_LANDED)
        self.controller.open_reply_gate()

    def paste_missed(self) -> None:
        """The same delivery, with the synthetic Ctrl+V refused: the Ctrl+V is
        the user's now, and the gate still opens - the payload is out either way."""
        self.controller.set_loop_state(LoopState.AUTO_INSERT, OUTBOUND_READY)
        self.controller.set_loop_state(LoopState.MANUAL_INSERT, PASTE_MISSED)
        self.controller.open_reply_gate()

    # -- what the pins read ---------------------------------------------------

    @property
    def lines(self) -> list[str]:
        return [entry.text for entry in self.controller.harness_log]

    @property
    def states(self) -> list[LoopState]:
        return self.view.loop_states

    def assert_mirrored(self) -> None:
        """The deque and the pane hold the same story in the same order."""
        assert [entry.text for entry in self.view.log_entries] == self.lines


def scenario(
    view: FakeAutomationView,
    *,
    detectors: tuple[str, ...] = ("busy",),
    captures: tuple[TemplateKind, ...] = (COPY,),
) -> Scenario:
    """A controller wired the way a shell wires it, minus the screen."""
    fires: list[None] = []
    controller = AutomationController(
        view=view,
        has_appearance=lambda kind: kind in captures,
        on_fire=lambda: fires.append(None),
    )
    controller.active_detectors = detectors
    return Scenario(controller, view, fires)


# -- the two roads to an arm ---------------------------------------------------


def test_an_icon_finish_narrates_paste_arm_and_one_fire(view: FakeAutomationView) -> None:
    """The commonest turn there is: pasted, the reasoning icon shows up, it
    goes away for two ticks, the auto-copy flow fires once."""
    s = scenario(view)

    s.paste_landed()
    s.busy(BusyState.MATCH)
    s.busy(BusyState.CHANGED)
    s.busy(BusyState.CHANGED)
    s.controller.end_flow()

    assert s.lines == [
        "IDLE → AUTO_INSERT — an outbound payload is ready to go into the chat box",
        "AUTO_INSERT → WAIT_SEND — the payload was pasted into the chat box",
        "auto-copy trigger armed: a busy/idle icon shows the model generating",
        "WAIT_SEND → WAIT_GENERATE — a busy/idle icon shows the model generating",
        "WAIT_GENERATE → AUTO_COPY — every live detector said the model stopped on "
        "two ticks running",
    ]
    assert s.states == [
        LoopState.AUTO_INSERT,
        LoopState.WAIT_SEND,
        LoopState.WAIT_GENERATE,
        LoopState.AUTO_COPY,
    ]
    assert s.fires == [None]
    s.assert_mirrored()


def test_a_stale_only_service_narrates_the_streak_that_armed_it(
    view: FakeAutomationView,
) -> None:
    """No icon anywhere: the arm is an INFERENCE from a sustained large delta,
    and the log says which one it was, numbers included. The two ticks before
    the streak completes write nothing at all - a run that has not been
    sustained yet is not a decision."""
    s = scenario(view, detectors=("stale",))

    s.paste_landed()
    for _ in range(SEND_ARM_TICKS):
        s.big_delta()
    s.stale(StaleState.STALE)
    s.stale(StaleState.STALE)
    s.controller.end_flow()

    assert s.lines == [
        "IDLE → AUTO_INSERT — an outbound payload is ready to go into the chat box",
        "AUTO_INSERT → WAIT_SEND — the payload was pasted into the chat box",
        "auto-copy trigger armed: 3 sustained large frame deltas in a row (≥ 0.02)",
        "WAIT_SEND → WAIT_GENERATE — 3 sustained large frame deltas in a row (≥ 0.02)",
        "WAIT_GENERATE → AUTO_COPY — every live detector said the model stopped on "
        "two ticks running",
    ]
    assert s.states == [
        LoopState.AUTO_INSERT,
        LoopState.WAIT_SEND,
        LoopState.WAIT_GENERATE,
        LoopState.AUTO_COPY,
    ]
    assert s.fires == [None]
    s.assert_mirrored()


# -- the ready-to-send gate, both ways out -------------------------------------


def test_the_send_gate_narrates_hold_then_sighting_then_release(
    view: FakeAutomationView,
) -> None:
    """A service with a captured send button: the gate holds from the paste,
    the button is sighted, its disappearance is the user's Enter, and only then
    does finish detection run."""
    s = scenario(view, captures=(COPY, SEND_READY))

    s.paste_landed()
    s.send_ready(True)
    s.send_ready(False)
    s.busy(BusyState.MATCH)
    s.busy(BusyState.CHANGED)
    s.busy(BusyState.CHANGED)
    s.controller.end_flow()

    assert s.lines == [
        "IDLE → AUTO_INSERT — an outbound payload is ready to go into the chat box",
        "AUTO_INSERT → WAIT_SEND — the payload was pasted into the chat box",
        "holding finish detection until the send is seen - between the paste and your "
        "Enter the chat is still, and a still chat reads as finished",
        "the ready-to-send button is on screen: there is unsent text in the chat box, "
        "so the send has not happened yet",
        "the ready-to-send button was seen and is now gone: finish detection is "
        "released, and it starts from the send rather than from the paste",
        "WAIT_SEND → WAIT_GENERATE — the ready-to-send button went away, which is your Enter",
        "auto-copy trigger armed: a busy/idle icon shows the model generating",
        "WAIT_GENERATE → AUTO_COPY — every live detector said the model stopped on "
        "two ticks running",
    ]
    assert s.states == [
        LoopState.AUTO_INSERT,
        LoopState.WAIT_SEND,
        LoopState.WAIT_GENERATE,
        LoopState.AUTO_COPY,
    ]
    assert s.fires == [None]
    s.assert_mirrored()


def test_a_send_button_that_never_appears_times_the_gate_out_and_says_so(
    view: FakeAutomationView,
) -> None:
    """The gate may delay a session; it may never deadlock one. The timeout
    writes its own line - the same sentence the toast makes, so the user who
    dismissed the toast can still find out what happened - and the turn then
    finishes exactly as an ungated one would."""
    s = scenario(view, captures=(COPY, SEND_READY))

    s.paste_landed()
    for _ in range(SEND_GATE_TIMEOUT_TICKS):
        s.send_ready(False)
    s.busy(BusyState.MATCH)
    s.busy(BusyState.CHANGED)
    s.busy(BusyState.CHANGED)
    s.controller.end_flow()

    assert s.lines == [
        "IDLE → AUTO_INSERT — an outbound payload is ready to go into the chat box",
        "AUTO_INSERT → WAIT_SEND — the payload was pasted into the chat box",
        "holding finish detection until the send is seen - between the paste and your "
        "Enter the chat is still, and a still chat reads as finished",
        "gate timed out: the ready-to-send button never appeared after the paste - "
        "finish detection is running as usual",
        "auto-copy trigger armed: a busy/idle icon shows the model generating",
        "WAIT_SEND → WAIT_GENERATE — a busy/idle icon shows the model generating",
        "WAIT_GENERATE → AUTO_COPY — every live detector said the model stopped on "
        "two ticks running",
    ]
    assert s.states == [
        LoopState.AUTO_INSERT,
        LoopState.WAIT_SEND,
        LoopState.WAIT_GENERATE,
        LoopState.AUTO_COPY,
    ]
    assert s.fires == [None]
    s.assert_mirrored()


# -- the ghost filter, in narration form ---------------------------------------


def test_ticks_from_a_dead_poller_run_narrate_nothing_at_all(
    view: FakeAutomationView,
) -> None:
    """§4.2, read off the log: a cancelled run's in-flight probes are about a
    window the automation no longer drives, so they may neither arm, release a
    gate, nor advance a streak. The pin is that this scenario's lines are
    IDENTICAL to the clean icon finish above - the ghosts left no trace, and
    the fire that follows is still exactly one."""
    s = scenario(view)

    s.paste_landed()
    dead = s.controller.detector_generation
    s.controller.retarget_detectors()
    # Everything a live run would have said, stamped with the run that ended.
    s.controller.feed_probe("busy", BusyProbe(BusyState.MATCH, 0.2, True), dead)
    s.controller.feed_probe("busy", BusyProbe(BusyState.CHANGED, 0.2, False), dead)
    s.controller.feed_probe("send_ready", True, dead)

    s.busy(BusyState.MATCH)
    s.busy(BusyState.CHANGED)
    s.busy(BusyState.CHANGED)
    s.controller.end_flow()

    assert s.lines == [
        "IDLE → AUTO_INSERT — an outbound payload is ready to go into the chat box",
        "AUTO_INSERT → WAIT_SEND — the payload was pasted into the chat box",
        "auto-copy trigger armed: a busy/idle icon shows the model generating",
        "WAIT_SEND → WAIT_GENERATE — a busy/idle icon shows the model generating",
        "WAIT_GENERATE → AUTO_COPY — every live detector said the model stopped on "
        "two ticks running",
    ]
    assert s.states == [
        LoopState.AUTO_INSERT,
        LoopState.WAIT_SEND,
        LoopState.WAIT_GENERATE,
        LoopState.AUTO_COPY,
    ]
    assert s.fires == [None]
    s.assert_mirrored()


# -- the longest road, and the one that never fires ----------------------------


def test_a_manual_insert_proved_by_the_send_button_ends_in_manual_copy(
    view: FakeAutomationView,
) -> None:
    """The full nine-line story, and the one path here that must NOT fire.

    The synthetic Ctrl+V was refused, so the paste is the user's; the send
    button appearing proves they did it (the button only renders over a
    non-empty composer), its disappearance is their Enter, the model generates
    and stops - and the service has no captured copy button, so the harvest is
    the user's too. Four different roads reach ``MANUAL_COPY`` and the rail
    draws one box for all of them: the log is where they are told apart.
    """
    s = scenario(view, captures=(SEND_READY,))

    s.paste_missed()
    s.send_ready(True)
    s.send_ready(False)
    s.busy(BusyState.MATCH)
    s.busy(BusyState.CHANGED)
    s.busy(BusyState.CHANGED)

    assert s.lines == [
        "IDLE → AUTO_INSERT — an outbound payload is ready to go into the chat box",
        "AUTO_INSERT → MANUAL_INSERT — the chat box was focused but the synthetic "
        "Ctrl+V did not go through",
        "holding finish detection until the send is seen - between the paste and your "
        "Enter the chat is still, and a still chat reads as finished",
        "the ready-to-send button is on screen: there is unsent text in the chat box, "
        "so the send has not happened yet",
        "MANUAL_INSERT → WAIT_SEND — the ready-to-send button appeared, which proves "
        "your paste landed",
        "the ready-to-send button was seen and is now gone: finish detection is "
        "released, and it starts from the send rather than from the paste",
        "WAIT_SEND → WAIT_GENERATE — the ready-to-send button went away, which is your Enter",
        "auto-copy trigger armed: a busy/idle icon shows the model generating",
        "WAIT_GENERATE → MANUAL_COPY — no copy button is captured for this service, so "
        "there is nothing to click (capture one in F2)",
    ]
    assert s.states == [
        LoopState.AUTO_INSERT,
        LoopState.MANUAL_INSERT,
        LoopState.WAIT_SEND,
        LoopState.WAIT_GENERATE,
        LoopState.MANUAL_COPY,
    ]
    # Finished, and nothing to click: the flow never starts.
    assert s.fires == []
    s.assert_mirrored()
